version: '3'

services:
  logic:
    build:
      context: .
      dockerfile: ./backend/logic/Dockerfile
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - ./backend/logic:/app