version: '3'

volumes:
  ticket_postgres_data: {}

networks:
  ticketnetwork:
    driver: bridge

services:
  web:
    container_name: "nginx"
    image: nginx:alpine
    depends_on:
      - logic
      - telegram
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ticketnetwork

  logic:
    build:
      context: .
      dockerfile: ./backend/logic/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logic/app:/app
    networks:
      - ticketnetwork
    depends_on:
      - db
      - rabbitmq

  telegram:
    build:
      context: .
      dockerfile: ./backend/telegram/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8001:8001"
    volumes:
      - ./backend/telegram/app:/app
    networks:
      - ticketnetwork
    depends_on:
      - rabbitmq
      
  db:
    image: "postgres:15.4-alpine3.18"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ticket_postgres_data:/var/lib/postgresql/data
    networks:
      - ticketnetwork

  rabbitmq:
    image: "rabbitmq:3.10.7-management"
    container_name: "myrabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ticketnetwork