version: '3'

volumes:
  ticket_postgres_data: {}

networks:
  ticketnetwork:

services:
  logic:
    build:
      context: .
      dockerfile: ./backend/logic/Dockerfile
    env_file:
      - ./.env
    ports:
      - "80:80"
    volumes:
      - ./backend/logic/app:/app
    networks:
      - ticketnetwork
    depends_on:
      - db
  db:
    image: "postgres:15.4-alpine3.18"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ticket_postgres_data:/var/lib/postgresql/data
    networks:
      - ticketnetwork